### ISSUE TITLE
ClassNotFoundException: fr.minuskube.iv.SmartInventory

### ISSUE THREAD

**Issue by Matix-Media** [MinusKube/SmartInvs#172]
Hi!

I'm currently starting to learn SmartInv and I get this error:
```
java.lang.NoClassDefFoundError: fr/minuskube/inv/SmartInventory
        at net.matixmedia.mlgrush.gamestates.LobbyGameState.createGUI(LobbyGameState.java:89) ~[?:?]
        at net.matixmedia.mlgrush.gamestates.LobbyGameState.<init>(LobbyGameState.java:85) ~[?:?]
        at net.matixmedia.mlgrush.Main.gameStateRegistration(Main.java:121) ~[?:?]
        at net.matixmedia.mlgrush.Main.onEnable(Main.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:769) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.Bukkit.reload(Bukkit.java:556) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: fr.minuskube.inv.SmartInventory
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        ... 20 more
```

I'm using Minecraft Paper 1.8.8. I use Maven as my dependency manager:
```xml
<dependency>
    <groupId>fr.minuskube.inv</groupId>
    <artifactId>smart-invs</artifactId>
    <version>1.2.7</version>
</dependency>
```

The function which is raising the error:
```java
private void createGUI() {
        SmartInventory inv = SmartInventory.builder()
                .id("map_selection_screen")
                .size(5, 9)
                .title(ChatColor.DARK_AQUA + "Select a map:")
                .build();
    }
```

Does someone know what I am doing wrong? Thank you in advice.

**Comment by Matix-Media** [comment]
Okay, so I fixed this issue by using the maven-shade-plugin and simply putting my plugin and SmartInv together in an uber-jar

**Comment by titivermeesch** [comment]
> Okay, so I fixed this issue by using the maven-shade-plugin and simply putting my plugin and SmartInv together in an uber-jar

That is indeed what you should do if the server does not have the plugin itself. For people using Gradle, [this](https://imperceptiblethoughts.com/shadow/) is a good solution
