### ISSUE TITLE
StackOverflowError: null

### ISSUE THREAD

**Issue by Rndstad** [MinusKube/SmartInvs#44]
```
04.02 20:16:48 [Server] ERROR Error occurred while enabling networkreportgui v1.0 (Is it up to date?)
04.02 20:16:48 [Server] INFO java.lang.StackOverflowError: null
04.02 20:16:48 [Server] INFO at fr.minuskube.inv.SmartInventory$Builder.<init>(SmartInventory.java:94) ~[?:?]
04.02 20:16:48 [Server] INFO at fr.minuskube.inv.SmartInventory.builder(SmartInventory.java:92) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:21) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
04.02 20:16:48 [Server] INFO at me.rndstad.networkreportgui.report.menus.ReportReasonInventory.<init>(ReportReasonInventory.java:22) ~[?:?]
```

**Comment by MinusKube** [comment]
You seem to call your `ReportReasonInventory`'s constructor inside this same constructor, this causes a never-ending recursive loop.

**Comment by MinusKube** [comment]
I'll close the issue since there is no more answer. Reopen it if you still need help on this problem :)

**Comment by Rndstad** [comment]
I'm sorry for the late respond. I have checked my code and I understand what you were saying. I have changed it and it works now, thank you very much! :) 👍
